---
title: Jpca1978.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Juan P. Correa
bio: 'Helping businesses expand: E-Health, Legal-Tech, Transportation, Fintech. Coffee
  lover and weekends hiker'
external-image: true
picture: https://gdurl.com/MdA9
your url: jpca1978.github.io
markdown: kramdown
highlighter: rouge
analytics-google: ''
disqus: mydisqus
facebook: jp.correa78
twitter: JuanPCorrea
linkedin: juan-pablo-correa-2a60a42
github: jpca1978
email: jp@ca78.me
width: normal
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
animation: true
gems:
- jemoji
- jekyll-mentions
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
- jekyll-paginate
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- indigo-gh-pages.zip
- Rakefile
- screen-shot.png
- travis.sh
